version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam --version
      - sam build
      #- sam package --s3-bucket testabcd123ab --output-template-file template.yml
      - sam deploy --no-confirm-changeset
