version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudnokku-serverless-resource"
s3_bucket = "cloudnokku-sam-lambda"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
