AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudNokku-sam-lambda

  Sample SAM Template for cloudNokku-sam-lambda

# Parameters:
#   InferenceImage:
#     Type: String
#   InferenceS3ModelLocation:
#     Type: String
#   ExecutionRoleArnParameter:
#     Type: String
#   SecurityGroups:
#     Type: String
#   Subnets:
#     Type: String
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
#   HelloWorldFunction:
#     Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#     Properties:
#       CodeUri: hello_world/
#       Handler: app.lambda_handler
#       Runtime: python3.7
      # Events:
      #   HelloWorld:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /hello
      #       Method: get
  
    
  # SagemakerInferenceModel:
  #   Type: 'AWS::SageMaker::Model'
  #   Properties:
  #     ModelName: "cloudnokku_inference_model"
  #     PrimaryContainer:
  #       Image: !Ref InferenceImage
  #       ModelDataUrl: !Ref InferenceS3ModelLocation
  #     ExecutionRoleArn: !Ref ExecutionRoleArnParameter 
  #     VpcConfig:
  #       SecurityGroupIds: !Split [',',!Ref SecurityGroups]
  #       Subnets: !Split [',',!Ref Subnets]
  
  # SagemakerEndPointConfigInference:
  #   Type: 'AWS::SageMaker::EndpointConfig'
  #   Properties:
  #     EndpointConfigName: "cloudnokku_inference_endpoint_config"
  #     ProductVariants:
  #       - InstanceType: "ml.t2.medium"
  #         InitialVariantWeight: 1
  #         InitialInstanceCount: 1
  #         ModelName: "cloudnokku_inference_model"
  #         VariantName: 'AllTraffic'
  #   DependsOn:
  #     - SagemakerInferenceModel

  # SagemakerEndpointInference:
  #   Type: "AWS::Sagemaker::Endpoint"
  #   Properties:
  #     EndpointName: "cloudnokku_inference_endpoint"
  #     EndpointConfigName: "cloudnokku_inference_endpoint_config"
  #   DependsOn:
  #     - SagemakerEndPointConfigInference

  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: my_layer
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  
